### ISSUE TITLE
add themed icon

### ISSUE THREAD

**Issue by foss-** [naoxio/inner_breeze#12]
With themed icons enabled, Inner Breeze shows a blank icon. Would be nice to add support for themed icon.

<img src="https://github.com/naoxio/inner_breeze/assets/5708172/24e0710b-460a-4482-b05f-6507f4cb4de4" width="250">

**Comment by waotzi** [comment]
Thank you, I'll look into it

**Comment by waotzi** [comment]
@foss- is that the pwa web version or the apk android version?

**Comment by foss-** [comment]
F-Droid install with KISS launcher.

**Comment by waotzi** [comment]
@foss- fixed in [1.0.8](https://github.com/naoxio/inner_breeze/releases/tag/1.0.8)

**Comment by foss-** [comment]
Looking great.

**Comment by waotzi** [comment]
thank you :smile:
