### ISSUE TITLE
Medium and Slow circle tempo not working properly

### ISSUE THREAD

**Issue by teasin951** [naoxio/inner_breeze#16]
When I set the breathing circle to medium or slow tempo, after starting a session the only thing I see is a "Get ready" sign and a gray rectangle underneath. You have to restart the app to get out of this. Android 14.

Update:
Ok so it also happens sometimes when I use the fast tempo. Or even mid session, I went through one round and after inhaling and holding for 15 sec, "Round 2:" sign appeared but only a gray rectangle underneath. I also noticed that the sound keeps playing normally.

**Comment by waotzi** [comment]
There appeared to be a bug with the breathing circle in the 1.0.9 version on lower. could you try again with 1.0.10 and let me know if the issue has been fixed :smile: 

thank you for the bug report

**Comment by teasin951** [comment]
Oh I'm sorry, I simply downloaded the newest version from F-Droid 😅. Ok I will try the 1.0.10

**Comment by waotzi** [comment]
No problem at all, I made the fix on the same day on you submitted the issue. If any issues persist please make another github issue :+1:
