### ISSUE TITLE
Add slower breathing rates

### ISSUE THREAD

**Issue by itzgoldenleonard** [naoxio/inner_breeze#19]
This app is great and minimal, but even the breathing in step 1 feels rushed. Medium and high are practically hyperventilation and even slow feels like I have to rush it. I'm not so familiar with the Wim Hof method, but the app says that you should fill your lungs up fully and there's just not time for that.

Please add another breathing rate 2 or 3 times slower than the slow preset, or just let me pick it myself. Or change the instructions if I'm supposed to breathe quickly and shallowly.

**Comment by waotzi** [comment]
thank you for the feedback, i'll improve the breathing slider to allow for more diverse breathing speeds.

However I should note that in the wim hof breathing method you are meant to hyperventilate in step 1, it is part of the process :smile: 

See the guided breathing tutorial by Wim Hof below:

https://www.youtube.com/watch?v=tybOi4hjZFQ&pp=ygUYd2ltIGhvZiBicmVhdGhpbmcgbWV0aG9k

**Comment by CapSel** [comment]
I need at least 5s breathes. Should I reopen this issue or create new one?
