### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [naoxio/inner_breeze#32]
```
diff -r /tmp/tmp69_egfdb/tmp_binaries_io.naox.inbe_24.binary/content/assets/flutter_assets/lib/i18n/en_US.json /tmp/tmp69_egfdb/tmp_io.naox.inbe_24/content/assets/flutter_assets/lib/i18n/en_US.json
39c39
<   "rounds_label": "Rounds",
---
>   "rounds_label": "Rounds: ",
```

Could you please take a look? A json file is different. Thanks!

**Comment by waozi-dev** [comment]
hi that's my bad. I was careless. I was lazy to make a new release when i noticed i made a string error, so i replaced the latest tag that f-droid must have grabbed beforehand and now they are conflicting.

it should be okay again once I make a new release

**Comment by waozi-dev** [comment]
should be fine again with the release of 1.2.6, thank you for reporting so quickly

**Comment by linsui** [comment]
Thanks!

**Comment by waozi-dev** [comment]
@linsui hi it's been 6 days since the release but the f-droid Version has not been updated yet. Are there any other issues?

**Comment by linsui** [comment]
No, there is no other issues. I don't know why it takes so long. We are all waiting for the update.

**Comment by waozi-dev** [comment]
Oh okay, thanks a lot for the update!

**Comment by linsui** [comment]
https://monitor.f-droid.org/builds/log/io.naox.inbe/30#site-footer It seems the flutter submodule is outdated. Could you please take a look? Thanks!

**Comment by waozi-dev** [comment]
@linsui thank you for letting me know, i'll update the submodule now

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/7166030457 The build failed with a different error...

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/b81f4ae7223d8c8869218602d217b2ab88ad8227

**Comment by waozixyz** [comment]
@licaon-kter thank you!

**Comment by licaon-kter** [comment]
Tag 1.4.1 but versionName and Code still 1.4.0?

**Comment by waozixyz** [comment]
sorry about that, i let a new contributor take over and he made a mistake, will fix it now

**Comment by linsui** [comment]
Thanks!
