### ISSUE TITLE
Tempo Adjustment

### ISSUE THREAD

**Issue by condean** [naoxio/inner_breeze#42]
I absolutely LOVE Inner Breeze! The app is almost perfect for me and I've shared it with all my friends and family.

One slight change that would be much appreciated is the ability to further adjust the tempo setting.  All I would really want personally is another setting between 'Fast' and 'Rapid'.  But ideally I think having the slider be infinetly adjustable would be the most useful for all users.  

Thanks so much for this amazing app! You're doing the world a massive service by making the Wim Hoff method more accessible for everyone!

**Comment by waozi-dev** [comment]
HI thank you for the feedback, you are right that the slider should be more precise, I'll add this feature when I get to it. Cheers
