### ISSUE TITLE
Screen timeout option

### ISSUE THREAD

**Issue by MrEddX** [naoxio/inner_breeze#5]
Great app!

It is very useful for me during preparation before climbing mountain peaks, especially in cold temperatures and bad weather conditions.

**So my question is:** _Is it possible to add an option in the settings to prevent the phone screen from going off while the app is being used?_

Thanks.

**Comment by waotzi** [comment]
@MrEddX hi that's a great feature request! I'll make sure to add that in the next update :smile:

**Comment by waotzi** [comment]
added a wakelock setting which is on by default when you start an exercise, so the screen doesn't timeout, thank you for pointing this out! 

The update is at v1.0.4, let me know if you find any more issues!
