### ISSUE TITLE
Add Meditation Keyword for search in F-droid

### ISSUE THREAD

**Issue by NameLessGO** [naoxio/inner_breeze#6]
Because most people search first for meditation, your app won't appear because it does not contain the keyword in the description

From your F-droid page:

> Elevate your Wim Hof breathing practice.

> Discover the simplicity of breath with Inner Breeze, a dedicated app to guide and track your Wim Hof Breathing Method journey. Tailored to both novices and experienced practitioners, Inner Breeze offers intuitive features to enhance your breathing exercises. From personalized tempo settings to insightful tracking, elevate your mindfulness and unlock the transformative power of breath. Inner Breeze is more than just an app; it's your daily oasis of calm and invigoration.

A great place to put would be: ... A dedicated meditation app to guide and track your wim hof breathing method...

The following images are a search with the term "Meditation" and "breathing" will find

![Screenshot_20231109_223603_Droid-ify.jpg](https://github.com/naoxio/inner_breeze/assets/66227691/d3fdfb57-703c-4c7b-ad9d-64eb1591a237)

![Screenshot_20231109_223557_Droid-ify.jpg](https://github.com/naoxio/inner_breeze/assets/66227691/2e05a480-f800-41c9-ad72-052b4a7dda72)

**Comment by NameLessGO** [comment]
Sorry this was very arrogant by me, will close the issue

**Comment by waotzi** [comment]
@NameLessGO hi thank you for the feedback! You are right about the keywords. I'll update it when I get around it

**Comment by waotzi** [comment]
i updated the description, i hope it's better now. feel free to give more feedback at any time :smile:
